services:
  - type: web
    name: mp-reactif
    env: docker
    plan: free
    branch: main
    envVars:

      - key: SPRING_REDIS_HOST
        sync: false
      - key: SPRING_REDIS_PORT
        sync: false
      - key: SPRING_REDIS_PASSWORD
        sync: false
      - key: SPRING_KAFKA_BOOTSTRAP_SERVERS
        sync: false
    autoDeploy: true
